/** Sitting drop: two stacked circles, no ear lobes. Demo recipe for the lab. */
export const recipe = {
  schemaVersion: 0,
  tag: "drop-blob",
  body: [
    { type: "circle", id: "head", x: 0, y: 0, r: 56 },
    { type: "circle", id: "belly", x: 0, y: 28, r: 52 },
    { type: "smin", id: "mass", a: "head", b: "belly", k: 28 },
  ],
  face: { size: 1.28, gap: 2.55, height: 1, eyeWidth: 0.82, eyeHeight: 1.32 },
  states: {
    idle: {
      turn: -10,
      tilt: -6,
      roll: 8,
      scale: 1.06,
      eyeScale: 1.28,
      gazeX: 0,
      gazeY: 0,
      gazeMin: 2500,
      gazeMax: 5500,
      bounce: 0.01,
      overlay: "none",
      spin: 0,
      shake: 0,
      squash: 0.01,
      zoom: 1,
    },
    working: {
      turn: -12,
      tilt: 2,
      roll: 6,
      scale: 1.04,
      eyeScale: 1.22,
      gazeX: 6,
      gazeY: 4,
      gazeMin: 1200,
      gazeMax: 2200,
      bounce: 0.007,
      overlay: "sweep",
      spin: 0.2,
      shake: 0,
      squash: 0.008,
      zoom: 1,
    },
    notifying: {
      turn: -12,
      tilt: -8,
      roll: 12,
      scale: 1.1,
      eyeScale: 1.32,
      gazeX: 6,
      gazeY: -3,
      gazeMin: 1000,
      gazeMax: 2000,
      bounce: 0.024,
      overlay: "sweep",
      spin: 0,
      shake: 0,
      squash: 0.016,
      zoom: 1,
    },
    alerting: {
      turn: -14,
      tilt: 0,
      roll: -14,
      scale: 1.12,
      eyeScale: 1.42,
      gazeX: 12,
      gazeY: 4,
      gazeMin: 500,
      gazeMax: 1100,
      bounce: 0.03,
      overlay: "none",
      spin: 0,
      shake: 1,
      squash: 0.02,
      zoom: 1,
    },
  },
  blink: { min: 6000, off: ["alerting"] },
  mouthless: [],
  freezeOverlays: ["orbit", "radar", "progress"],
};

export default recipe;
